DROP VIEW IF EXISTS V_MATCHES_CITY_CLEAN;

CREATE VIEW V_MATCHES_CITY_CLEAN AS
SELECT
    M.*,
    COALESCE(V.CITY, M.CITY, 'UNKNOWN') AS CITY_CLEAN
FROM MATCHES M
LEFT JOIN V_VENUES_CLEAN V
    ON V.VENUE = M.VENUE;
    